Working version before big refactor to use screen bash -c $CMD

diff --git a/drsync b/drsync
--- a/drsync
+++ b/drsync
@@ -1,4 +1,6 @@
 #!/usr/bin/env bash
+# exit if we hit any error
+set -e
 
 if [ ! -d "$HOME/.drsync_transfers" ] 
 then
@@ -10,6 +12,9 @@ prev_transfer_num=`ls "$HOME/.drsync_transfers" | sort --version-sort | grep "dr
 transfer_num=$((prev_transfer_num+1))
 session_name=`printf 'drsync.%06g' "$transfer_num"`
 logfile="$HOME/.drsync_transfers/$session_name"
+
+# create a trap the will fire on error that kills the screen session, so that if there is some error that happens in this function we don't get left with a floating detatched screen that isn't working on anything
+trap 'screen -S "$session_name" -X quit; echo "Error encountered in drsync execution, killing the screen session and exiting."' ERR
 
 # touch logfile to reserve number in case another job launches before logging starts
 touch "$logfile"
@@ -25,14 +30,14 @@ screen -dmS "$session_name" bash
 arg_arr=()
 for arg in "$@"; do
     #the shell eats the escape characters when things get passed in so we need to put them back
-    arg_escaped=$(echo "$arg" | sed -e 's/\\/\\\\/g' -e 's/ /\\ /g' -e 's/!/\\!/g' -e 's/(/\\(/g' -e 's/)/\\)/g' -e 's/#/\\#/g')
+    arg_escaped=$(echo "$arg" | sed -e 's/\\/\\\\/g' -e 's/ /\\ /g' -e 's/!/\\!/g' -e 's/(/\\(/g' -e 's/)/\\)/g' -e 's/#/\\#/g' -e 's/\&/\\&/g' -e 's/\$/\\$/g' -e 's/{/\\{/g' -e 's/}/\\}/g')
     arg_arr+=($arg_escaped)
 done
 args=$(printf '%s ' "${arg_arr[@]}")
-source=$(echo "${@:(-2):1}" | sed -e 's/\\/\\\\/g' -e 's/ /\\ /g' -e 's/!/\\!/g' -e 's/(/\\(/g' -e 's/)/\\)/g' -e 's/#/\\#/g')
-source_dir=$(echo "${@:(-2):1}" | sed -e 's/\\/\\\\/g' -e 's/ /\\ /g' -e 's/!/\\!/g' -e 's/(/\\(/g' -e 's/)/\\)/g' -e 's/#/\\#/g' | grep -o '.*/')
-target=$(echo "${@: -1}" | sed -e 's/\\/\\\\/g' -e 's/ /\\ /g' -e 's/!/\\!/g' -e 's/(/\\(/g' -e 's/)/\\)/g' -e 's/#/\\#/g')
-working=$(echo "$PWD" | sed -e 's/\\/\\\\/g' -e 's/ /\\ /g' -e 's/!/\\!/g' -e 's/(/\\(/g' -e 's/)/\\)/g' -e 's/#/\\#/g')
+source=$(echo "${@:(-2):1}" | sed -e 's/\\/\\\\/g' -e 's/ /\\ /g' -e 's/!/\\!/g' -e 's/(/\\(/g' -e 's/)/\\)/g' -e 's/#/\\#/g' -e 's/\&/\\&/g' -e 's/\$/\\$/g' -e 's/{/\\{/g' -e 's/}/\\}/g')
+source_dir=$(echo "${@:(-2):1}" | sed -e 's/\\/\\\\/g' -e 's/ /\\ /g' -e 's/!/\\!/g' -e 's/(/\\(/g' -e 's/)/\\)/g' -e 's/#/\\#/g' -e 's/\&/\\&/g' -e 's/\$/\\$/g' -e 's/{/\\{/g' -e 's/}/\\}/g' | grep -o '.*/')
+target=$(echo "${@: -1}" | sed -e 's/\\/\\\\/g' -e 's/ /\\ /g' -e 's/!/\\!/g' -e 's/(/\\(/g' -e 's/)/\\)/g' -e 's/#/\\#/g' -e 's/\&/\\&/g' -e 's/\$/\\$/g' -e 's/{/\\{/g' -e 's/}/\\}/g')
+working=$(echo "$PWD" | sed -e 's/\\/\\\\/g' -e 's/ /\\ /g' -e 's/!/\\!/g' -e 's/(/\\(/g' -e 's/)/\\)/g' -e 's/#/\\#/g' -e 's/\&/\\&/g' -e 's/\$/\\$/g' -e 's/{/\\{/g' -e 's/}/\\}/g')
 commands=$(printf "trap 'sleep 5; exit' ERR; cd %s; rsync --info=progress2 --no-inc-recursive %s; sleep 5; exit;" "$working" "$args")
 
 # if the user sends the --remove-source-files rsync option, then we'll send a command that cleans up the leftover empty directories.
